android.useAndroidX=true
android.enableJetifier=true
# Gradle Daemon ကို RAM 4GB အထိ အသုံးပြုခွင့်ပေးပြီး compiler ဝန်မပိအောင် လုပ်ခြင်း
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError

# Dex compiler (D8) ကိုလည်း RAM အပို သုံးခွင့်ပေးခြင်း
android.useDexArchive=true
