name: Android APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: bash ./gradlew assembleDebug

    - name: Upload to WeTransfer
      id: wetransfer
      run: |
        # WeTransfer ရဲ့ အခမဲ့စနစ်ဖြစ်တဲ့ wetransfer_cli ကို သုံးပြီး ဖိုင်တင်ခြင်း
        curl -fsSL https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh | sh
        ./transfer wet_base app/build/outputs/apk/debug/app-debug.apk > link.txt
        echo "WETRANSFER_URL=$(cat link.txt)" >> $GITHUB_ENV

    - name: Send Direct Link to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🎉 Android Build အောင်မြင်သွားပါပြီ!
          
          📦 Browser ထဲ ဝင်စရာမလိုဘဲ တန်းနှိပ်ဒေါင်းရန် မြန်နှုန်းမြင့် Link:
          ${{ env.WETRANSFER_URL }}
          
